# Generated by Django 6.0.4 on 2026-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Jobs", "0002_repair_job_description_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("reviewed", "Reviewed"),
                    ("shortlisted", "Shortlisted"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
